name: Terraform Format and Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    name: Terraform Fmt & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # or your desired version

      - name: Initialize Terraform
        run: terraform init

      - name: Check Terraform Format
        run: terraform fmt -check -recursive

      - name: Validate Terraform
        run: terraform validate
